$b64 = "VHJ5IHsKICAgICMgQ2hlY2sgaWYgdGhlIHVzZXIgaGFzIGFkbWluaXN0cmF0aXZlIHJpZ2h0cwogICAgJGlzQWRtaW4gPSAoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzUHJpbmNpcGFsXSBbU2VjdXJpdHkuUHJpbmNpcGFsLldpbmRvd3NJZGVudGl0eV06OkdldEN1cnJlbnQoKSkuSXNJblJvbGUoW1NlY3VyaXR5LlByaW5jaXBhbC5XaW5kb3dzQnVpbHRJblJvbGVdICJBZG1pbmlzdHJhdG9yIikKICAgIAogICAgSWYgKC1Ob3QgJGlzQWRtaW4pIHsKICAgICAgICBXcml0ZS1Ib3N0ICJUaGlzIHNjcmlwdCBtdXN0IGJlIHJ1biBhcyBhbiBhZG1pbmlzdHJhdG9yLiIgLUZvcmVncm91bmRDb2xvciBSZWQKICAgICAgICBFeGl0IDEKICAgIH0KICAgIGVsc2UgewogICAgICAgIFdyaXRlLUhvc3QgIkFkbWluaXN0cmF0b3IgcmlnaHRzOiBFbmFibGVkIiAtRm9yZWdyb3VuZENvbG9yIEdyZWVuCiAgICB9Cgp9IENhdGNoIHsKICAgIFdyaXRlLUhvc3QgIkFuIGVycm9yIG9jY3VycmVkOiAkXyIgLUZvcmVncm91bmRDb2xvciBSZWQKfQo="
Set-Content -Path 1IlIlIIIIIlIlIl1.txt -Value $b64
$decoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String((Get-Content 1IlIlIIIIIlIlIl1.txt)))
Set-Content -Path lll1IIlllllIlIII.ps1 -Value $decoded
powershell -ExecutionPolicy Bypass -File lll1IIlllllIlIII.ps1
Remove-Item 1IlIlIIIIIlIlIl1.txt, lll1IIlllllIlIII.ps1
